version: '3.3'

services:

  wordpress:
    container_name: lyucean_blog_wp
    image: wordpress
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG}
    volumes:
      - ./app/wordpress:/var/www/html
      - ./app/my_plugin:/var/www/html/wp-content/plugins/my_plugin
      - ./app/my_theme:/var/www/html/wp-content/themes/my_theme
    labels:
      - traefik.enable=true
      - traefik.http.routers.wordpress.rule=Host(`lyucean.com`)
      - traefik.http.routers.wordpress.entrypoints=websecure
      - traefik.http.routers.wordpress.tls=true
      - traefik.http.routers.wordpress.tls.certresolver=letsencrypt
      - traefik.http.services.wordpress.loadbalancer.server.port=80
    networks:
      - web

  mysql:
    container_name: lyucean_blog_mysql
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - lyucean-mysql-data:/var/lib/mysql
    networks:
      - web
      -
  ssh:
    container_name: lyucean_blog_ssh
    image: rastasheep/ubuntu-sshd:18.04  # Образ легковесного SSH-сервера
    restart: unless-stopped
    ports:
      - "2222:22"  # Пробрасываем порт 22 контейнера на порт 2222 хоста
    volumes:
      - ./:/project  # Монтируем корневую папку проекта в контейнер
    environment:
      - ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}  # Устанавливаем пароль для root (замените на свой)
    networks:
      - web
    command: /usr/sbin/sshd -D


volumes:
  lyucean-mysql-data: # Определяем том для сохранения данных MySQL

networks:
  web:
    external: true # стандартная для всех на этом сервере