version: '3.3'

services:
  nginx-single:
    profiles: ["single"]
    image: nginx:latest
    container_name: lyucean-nginx-page
    hostname: lyucean.com
    volumes:
      - ./public:/usr/share/nginx/html
    environment:
      - NGINX_HOST=lyucean.com
      - NGINX_INDEX=index.html
      - NGINX_ROOT=/usr/share/nginx/html
      - NGINX_PORT=80
    labels:
      - traefik.enable=true
      - traefik.http.routers.nginx-lyucean.rule=Host(`lyucean.com`)
      - traefik.http.routers.nginx-lyucean.entrypoints=websecure
      - traefik.http.routers.nginx-lyucean.tls=true
      - traefik.http.routers.nginx-lyucean.tls.certresolver=letsencrypt
      - traefik.http.services.nginx-lyucean.loadbalancer.server.port=80
    networks:
      - web

  nginx-lyucean:
    profiles: ["blog"]
    image: nginx:latest
    container_name: lyucean-nginx-blog
    hostname: lyucean.com
    volumes:
      - ./app:/usr/share/nginx/html
    environment:
      - NGINX_HOST=blog.lyucean.com
      - NGINX_INDEX=index.html
      - NGINX_ROOT=/usr/share/nginx/html
      - NGINX_PORT=80
    labels:
      - traefik.enable=true
      - traefik.http.routers.nginx-lyucean.rule=Host(`blog.lyucean.com`)
      - traefik.http.routers.nginx-lyucean.entrypoints=websecure
      - traefik.http.routers.nginx-lyucean.tls=true
      - traefik.http.routers.nginx-lyucean.tls.certresolver=letsencrypt
      - traefik.http.services.nginx-lyucean.loadbalancer.server.port=80
    networks:
      - web

networks:
  web:
    external: true # стандартная для всех на этом сервере