version: '3.3'

services:

  nginx-page:
    container_name: lyucean_page
    image: nginx:latest
    hostname: lyucean.com
    volumes:
      - ./:/usr/share/nginx/html
    environment:
      - NGINX_HOST=lyucean.com
      - NGINX_INDEX=index.html
      - NGINX_ROOT=/usr/share/nginx/html
      - NGINX_PORT=80
    labels:
      - traefik.enable=true
      - traefik.http.routers.nginx-page.rule=Host(`lyucean.com`)
      - traefik.http.routers.nginx-page.entrypoints=websecure
      - traefik.http.routers.nginx-page.tls=true
      - traefik.http.routers.nginx-page.tls.certresolver=letsencrypt
      - traefik.http.services.nginx-page.loadbalancer.server.port=80
    networks:
      - web

networks:
  web:
    external: true # стандартная для всех на этом сервере


