name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Run test script
        run: pwd

  deploy:
    runs-on: ubuntu-latest
    needs: [test]

    steps:

      - name: Run a one-line deploy script
        run: ls -al

      - name: Run a multi-line deploy script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
