name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Run test script
        run: pwd

  deploy:
    runs-on: ubuntu-latest
    needs: [test]

    steps:

      - name: Clone Repo
        run: actions/checkout@v3

      - name: Run a one-line deploy script
        run: ls -al
