name: Deployment

concurrency: production

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-host:
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: https://lyucean.com

    steps:
    - name: Testing the accessibility of the host
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: whoami

  deploy:
    runs-on: self-hosted
    environment: production
    needs: [test-host]

    steps:

      - name: Clone Repo
        uses: actions/checkout@v3

      - name: CP file
        run: cp -Rv ./* /var/www/lyucean.com/

      - name: ls folder
        run: ls -al /var/www/lyucean.com/
