name: Deployment

concurrency: production

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: http://lyucean.com

    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: whoami

  deploy:
    runs-on: self-hosted
    environment: production
    needs: [test]

    steps:

      - name: Clone Repo
        uses: actions/checkout@v3

      - name: Run pwd
        run: pwd
        
      - name: Run history
        run: history

      - name: Run a one-line deploy script
        run: ls -al
